### PR TITLE
Fix #128

### LINKED ISSUE #128: binary_collection move invalidates iterator
**Describe the bug**
Moving `binary_collection` invalidates any iterator pointing to its elements. This is because we store a pointer to it in the iterator structure. The fix is to store data pointer and size instead.

### PR DESCRIPTION
**Pull request by amallia**
I clang-format'd it. So it looks worst than it actually is...

### CODE REVIEW

File: include/pisa/binary_collection.hpp [hunk 1]
```diff
@@ -11,131 +11,129 @@
...
+            // file might be truncated
+            n          = std::min(n, size_t(m_data_size - pos));
+            auto begin = &m_data[pos];
+
+            m_next_pos = pos + n;
+            m_cur_seq  = S(begin, begin + n);
+        }
+
+        const pointer m_data;
+        size_t        m_data_size = 0, m_pos = 0, m_next_pos = 0;
```
Comment (elshize) [inline include/pisa/binary_collection.hpp:127]: I would avoid this in the future, it's inconsistent where to look for variable names: if we have a set of lines, then let's stick to it.

**Review by elshize — APPROVED** [review]
Looks good.
