### PR TITLE
Fix TBB leaks in tests

### LINKED ISSUE #265: Use task_scheduler_init in tests where TBB is used
Currently, tests that use TBB to, e.g., build a test index, fail with memory leaks when run with sanitizers.

The fix is to always include

```cpp
tbb::task_scheduler_init init(1);
```
at the beginning of each test (number of threads doesn't necessarily need to be 1).

### PR DESCRIPTION
**Pull request by elshize**
Fixes #265

There are still other problems that the sanitizer finds in the following tests:
```
The following tests FAILED:
	  5 - test_block_codecs:block_codecs (Failed)
	  9 - test_bmw_queries:block_max_wand (Failed)
	 25 - test_freq_index:freq_index (Failed)
	 43 - test_partition_fwd_index:copy_sequence (Failed)
	 44 - test_partition_fwd_index:Rearrange sequences (Failed)
	 46 - test_partitioned_sequence:partitioned_sequence (Failed)
	 54 - test_positive_sequence:positive_sequence (Failed)
```

Likely some of them (or all) are related to the problems clang static analyzer found: #263

### CODE REVIEW

File: test/test_forward_index_builder.cpp [hunk 1]
```diff
@@ -157,6 +167,7 @@ void write_batch(std::string const &basename,
 
 TEST_CASE("Merge forward index batches", "[parsing][forward_index]")
 {
+    tbb::task_scheduler_init init(2);
```
Comment (JMMackenzie) [inline test/test_forward_index_builder.cpp]: I don't think we even need to pass a number here, though it probably doesn't matter.

File: test/test_forward_index_builder.cpp [hunk 2]
```diff
@@ -298,6 +314,7 @@ TEST_CASE("Parse HTML content", "[parsing][forward_index][unit]")
 
 TEST_CASE("Build forward index", "[parsing][forward_index][integration]")
 {
+    tbb::task_scheduler_init init(2);
```
Comment (JMMackenzie) [inline test/test_forward_index_builder.cpp]: Same as above.

**Review by JMMackenzie — APPROVED** [review]

**Comment by elshize** [comment]
Thanks @JMMackenzie good point on the no. threads, I removed them.
