### PR TITLE
Bad alloc

### LINKED ISSUE #256: bad_alloc when using query terms
`queries` with `--terms` crashes.

I've more or less found the problem, but wasn't able to finish the fix tonight.

### PR DESCRIPTION
**Pull request by elshize**
Fixes #256

### CODE REVIEW

File: include/pisa/query/queries.hpp [hunk 1]
```diff
@@ -92,12 +92,13 @@ struct Query {
...
-    const std::optional<std::string> stopwords_filename,
-    const std::optional<std::string> stemmer_type) {
+    std::optional<std::string> const &terms_file,
+    std::optional<std::string> const &stopwords_filename,
+    std::optional<std::string> const &stemmer_type)
+{
     if (terms_file) {
-        auto term_processor = TermProcessor(terms_file, stopwords_filename, stemmer_type);
-        return [&](std::string const &query_line) {
+        return [&, term_processor = TermProcessor(terms_file, stopwords_filename, stemmer_type)](
```
Comment (gustingonzalez) [inline include/pisa/query/queries.hpp]: Sorry for this bug. This is due to `term_processor` is destroyed after exiting of the function, isn't it? In the other hand, looking again, would it be an adventage capturing only `&queries` instead `&`?

File: include/pisa/query/queries.hpp [hunk 2]
```diff
@@ -92,12 +92,13 @@ struct Query {
 
 [[nodiscard]] std::function<void(const std::string)> compute_parse_query_function(
```
Comment (gustingonzalez) [inline include/pisa/query/queries.hpp]: In the last PR it was pending to simplify the name of this function to `compute_query_parser`, `resolve_query_parser` or similar. Maybe this bug fix could be used to improve this too.

File: include/pisa/query/queries.hpp (hunk 1 above)
Comment (gustingonzalez) [inline include/pisa/query/queries.hpp]: Sorry for this bug introduced after refactoring. This is due to `term_processor` is destroyed after exiting of the function, isn't it? In the other hand, looking again, would it be an advantage capturing only `&queries` instead `&`?

File: include/pisa/query/queries.hpp [hunk 3]
```diff
@@ -92,12 +92,13 @@ struct Query {
...
-    const std::optional<std::string> terms_file,
-    const std::optional<std::string> stopwords_filename,
-    const std::optional<std::string> stemmer_type) {
+    std::optional<std::string> const &terms_file,
+    std::optional<std::string> const &stopwords_filename,
+    std::optional<std::string> const &stemmer_type)
+{
     if (terms_file) {
-        auto term_processor = TermProcessor(terms_file, stopwords_filename, stemmer_type);
-        return [&](std::string const &query_line) {
```
Comment (gustingonzalez) [inline include/pisa/query/queries.hpp:100]: Sorry for this bug introduced after refactoring. I understand that it was caused because `term_processor` was destroyed after exiting of the function, is that correct?

In the other hand, would it be an advantage capturing only `&queries` instead `&`?

Comment (elshize) [reply include/pisa/query/queries.hpp:100]: It might be a good idea to capture things one by one, especially when capturing by reference. Nevertheless, we have to move term processor into a generalized capture because there's no capture-by-move operator, like `&` for references and `=` for copies. the alternative to what I did is:
```cpp
auto term_processor = TermProcessor(terms_file, stopwords_filename, stemmer_type);
return [&queries, term_processor = std::move(term_processor)](
           std::string const &query_line) {
    queries.push_back(parse_query_terms(query_line, term_processor));
};
```
Here, you explicitly move what is previously constructed.

Comment (elshize) [reply include/pisa/query/queries.hpp:100]: On another note, we should be using some static code analyzer in our CI to find these things. I'm reasonably sure, say, `clang-tidy` would find this.

**Comment by amallia** [comment]
What I see in this PR:
- a fix for an UB (return a destroyed object)
- renamed function with something more meaningful 
- better code formatting

Travis was complaining and I should have fixed it. 

It looks good to me and thanks for the PR. We can merge 👍
