### PR TITLE
Fix deprecated TBB calls

### LINKED ISSUE #368: TBB task_scheduler_init has been deprecated
```
 #pragma message("TBB Warning: tbb/task_scheduler_init.h is deprecated. For details, please see Deprecated Features appendix in the TBB reference manual.")
```

I think we need to move to using `global_control` - https://software.intel.com/en-us/node/589744

### PR DESCRIPTION
**Pull request by JMMackenzie**
Fixes #368 by using the `tbb::global_control` class.

It seems that at alternative method would have been to use the `task_arena` but the current approach will work on a global basis (whereas task_arenas can limit threads on a per-arena basis) so this seemed like the best approach for now.

### CODE REVIEW

File: tools/evaluate_queries.cpp [hunk 1]
```diff
@@ -199,7 +199,7 @@ int main(int argc, const char** argv)
 
     CLI11_PARSE(app, argc, argv);
 
-    tbb::task_scheduler_init init(app.threads());
+    tbb::global_control control(tbb::global_control::max_allowed_parallelism, app.threads());
```
Comment (elshize) [inline tools/evaluate_queries.cpp]: Looking at the docs, it seems like the number of threads include the main thread:

> Limit total number of worker threads that can be active in the task scheduler to parameter value - 1

So I'm wondering whether we should increase it to `app.threads() + 1` since our main thread only waits for the others, so effectively you'd get one fewer worker than you'd expect. Does this make sense?

Comment (JMMackenzie) [reply tools/evaluate_queries.cpp]: Yep agreed. I have also explicitly stated "worker threads" in the printout (which is the passed thread count, ignoring the +1).

**Review by elshize — APPROVED** [review]

**Comment by elshize** [comment]
You have a clang-fmt error in one of the files: https://travis-ci.com/github/pisa-engine/pisa/jobs/336410476
